"""SQL format — write-only format that generates CREATE TABLE + INSERT statements"""

import re
from typing import Any, Iterator

from file_format.base import FileFormat, Record


class SQLFormat(FileFormat, format_name="sql", file_extensions=(".sql",)):
    """
    Write-only format. Generates SQL DDL + DML from an iterator of records.

    Buffers all records to infer column types before writing.
    """

    def __init__(
        self,
        table_name: str = "table",
        batch_size: int = 100,
        include_create_table: bool = True,
        encoding: str = "utf-8",
    ):
        self.table_name = table_name
        self.batch_size = batch_size
        self.include_create_table = include_create_table
        self.encoding = encoding
        self._column_types: dict[str, str] = {}

    def read(self, source: str) -> Iterator[Record]:
        raise NotImplementedError("SQLFormat is write-only")

    def write(self, records: Iterator[Record], destination: str) -> int:
        rows = list(records)
        if not rows:
            with open(destination, "w", encoding=self.encoding) as f:
                f.write("-- No data\n")
            return 0

        self._column_types = self._determine_column_types(rows)

        parts = ["-- Generated by file_format.SQLFormat", ""]
        if self.include_create_table:
            parts += ["-- Table structure", self._generate_create_table(), ""]
        parts += ["-- Data", self._generate_inserts(rows)]

        with open(destination, "w", encoding=self.encoding) as f:
            f.write("\n".join(parts))
        return len(rows)

    # -- SQL generation --

    def _generate_create_table(self) -> str:
        cols = ",\n".join(f"    {col} {dtype}" for col, dtype in self._column_types.items())
        return f"CREATE TABLE {self.table_name} (\n{cols}\n);"

    def _generate_inserts(self, rows: list[Record]) -> str:
        columns = list(rows[0].keys())
        col_list = ", ".join(columns)
        parts = []
        for i in range(0, len(rows), self.batch_size):
            batch = rows[i : i + self.batch_size]
            value_rows = []
            for row in batch:
                vals = ", ".join(self._format_value(row[c], c) for c in columns)
                value_rows.append(f"    ({vals})")
            parts.append(
                f"INSERT INTO {self.table_name} ({col_list})\nVALUES\n"
                + ",\n".join(value_rows)
                + ";"
            )
        return "\n\n".join(parts)

    # -- Type inference --

    def _determine_column_types(self, rows: list[Record]) -> dict[str, str]:
        column_types: dict[str, str] = {}
        for column in rows[0].keys():
            types_found: set[str] = set()
            max_len = 0
            for row in rows:
                raw = row[column]
                value = str(raw).strip() if raw is not None else "NULL"
                if value and value.upper() != "NULL":
                    dtype = self._detect_type(value)
                    types_found.add(dtype)
                    if "VARCHAR" in dtype:
                        max_len = max(max_len, len(value))

            if any("DATETIME" in t for t in types_found):
                column_types[column] = "DATETIME"
            elif any("DATE" in t for t in types_found):
                column_types[column] = "DATE"
            elif any("DECIMAL" in t for t in types_found):
                column_types[column] = "DECIMAL(15,4)"
            elif any("INT" in t for t in types_found):
                column_types[column] = "INT"
            elif any("CHAR(1)" in t for t in types_found):
                column_types[column] = "CHAR(1)"
            else:
                length = min(max(max_len * 2, 50), 1000)
                column_types[column] = f"VARCHAR({length})"
        return column_types

    def _detect_type(self, value: str) -> str:
        if re.match(r"^-?\d+$", value):
            return "INT"
        if re.match(r"^-?\d+\.\d+$", value):
            return "DECIMAL(10,4)"
        if re.match(r"^\d{4}-\d{2}-\d{2}$", value):
            return "DATE"
        if re.match(r"^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}", value):
            return "DATETIME"
        if value.upper() in {"TRUE", "FALSE", "T", "F", "Y", "N", "YES", "NO"}:
            return "CHAR(1)"
        length = min(max(len(value) * 2, 50), 1000)
        return f"VARCHAR({length})"

    def _format_value(self, value: Any, column: str) -> str:
        if value is None or str(value).strip().upper() in {"NULL", ""}:
            return "NULL"
        value_str = str(value).strip()
        dtype = self._column_types.get(column, "VARCHAR(255)")
        if dtype in {"INT", "DECIMAL", "DECIMAL(15,4)", "DECIMAL(10,4)"}:
            return value_str
        return "'" + value_str.replace("'", "''") + "'"
